language: android

env:
  global:
      secure: "N5zxhhaBa0W940cxO1GQBnh99Sxsl2w/AiCucP+xGZ7FqtGjrqD3ua3UI2F8vgxseXJ8/N/hXJSvxHbtDYlr+K2h7Khh8yQagwkgZwUFeiHvLjQZwnEhEQWraoWMW76rgN0dUr3Vtx+wv4zU4CbDRXt9QuIkVY409B3QUkk23uBwOPK8a+XTTfojoswpXIw0Po92ql8fU8ttc9lMX9mgHu5Sak8pzXimvxQ1K2RYCVEVngwexEm03MrRKExXjaxmfsslHdb0gdf6ro3rn+wiFsMrd67CfZ342MQUHLiQjH1Bh/Vi4FygNIbb/pwRcrnYaGFanfG5S/bAgQgmtR3WL6C9WQcnNK1LZafLXBJ8SXMGhTFUNViC3frYLKC82t8E5hFXj1G8WJLTRKOZX6IEX5Lx/h3cNl9HhZagSojrqaY7iNnq+9VZBSawx9rMgVmDksUWJ9sKCEjKoO9TqqIjVAN/ivNpkBs3UMRxz1++TsDL2QCreOi/JjD8szFDwOZqtLCB2pBIoMqY43vsz5ElYKTlJPj759D8Rj0BxhYEpKhmP9qGWUMQQJz0rG1cCQ5vP0XdfyfKCWEd7is5G94ezahaejcNS9GfUsZv2cAEPk0ry+LYwfK4GjdFxmT+yGizoY+X4Mrg9Xp45vAwNdz5PZDR6F/n2IPnfGn9AnoklSM="

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+

script:
  if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./gradlew build connectedCheck ; fi

addons:
  coverity_scan:
    project:
      name: data5tream/emoji-lib
      version: 1.0
      description: Emoji Support Library for Android

    notification_email: admin@7base.net

    #build_command_prepend: ./configure

    build_command: ./gradlew build connectedCheck

    branch_pattern: coverity_scan

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1952f97e9d115599a9b0
    on_success: change
    on_failure: always
    on_start: never
