language: android

env:
  global:
    secure: N5zxhhaBa0W940cxO1GQBnh99Sxsl2w/AiCucP+xGZ7FqtGjrqD3ua3UI2F8vgxseXJ8/N/hXJSvxHbtDYlr+K2h7Khh8yQagwkgZwUFeiHvLjQZwnEhEQWraoWMW76rgN0dUr3Vtx+wv4zU4CbDRXt9QuIkVY409B3QUkk23uBwOPK8a+XTTfojoswpXIw0Po92ql8fU8ttc9lMX9mgHu5Sak8pzXimvxQ1K2RYCVEVngwexEm03MrRKExXjaxmfsslHdb0gdf6ro3rn+wiFsMrd67CfZ342MQUHLiQjH1Bh/Vi4FygNIbb/pwRcrnYaGFanfG5S/bAgQgmtR3WL6C9WQcnNK1LZafLXBJ8SXMGhTFUNViC3frYLKC82t8E5hFXj1G8WJLTRKOZX6IEX5Lx/h3cNl9HhZagSojrqaY7iNnq+9VZBSawx9rMgVmDksUWJ9sKCEjKoO9TqqIjVAN/ivNpkBs3UMRxz1++TsDL2QCreOi/JjD8szFDwOZqtLCB2pBIoMqY43vsz5ElYKTlJPj759D8Rj0BxhYEpKhmP9qGWUMQQJz0rG1cCQ5vP0XdfyfKCWEd7is5G94ezahaejcNS9GfUsZv2cAEPk0ry+LYwfK4GjdFxmT+yGizoY+X4Mrg9Xp45vAwNdz5PZDR6F/n2IPnfGn9AnoklSM=

android:
  components:
  - platform-tools
  - build-tools-23.0.1
  - android-23
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository

  licenses:
  - android-sdk-license-.+

script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./gradlew build connectedCheck ;
  fi

addons:
  coverity_scan:
    project:
      name: Data5tream/emoji-lib
      version: 1.0
      description: Emoji Support Library for Android

    notification_email: admin@7base.net
    build_command: "./gradlew build connectedCheck"
    branch_pattern: coverity_scan
